substitutions:
  name: waveshare-bathroom
  friendly_name: Waveshare - BathRoom

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp32:
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: UART0
  level: DEBUG

api:
  encryption:
    key: "P746hgv+Q7QtReW8T5Xs5r39IpXMIQURSjoBSYf+hbs="

ota:
  - platform: esphome
    password: !secret waveshare_bathroom__ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Waveshare-Bathroom-Fallback"
captive_portal:

i2c:
  sda: GPIO8
  scl: GPIO9

ch422g:
  - id: ch422g_hub

display:
  - platform: mipi_rgb
    model: ESP32-S3-TOUCH-LCD-4.3
    id: main_display
    auto_clear_enabled: false
    update_interval: never

touchscreen:
  - platform: gt911
    id: main_touch
    display: main_display

    interrupt_pin: GPIO4

    reset_pin:
      ch422g: ch422g_hub
      number: 1
lvgl:
  displays:
    - main_display

  touchscreens:
    - touchscreen_id: main_touch

  widgets:
    - button:
        id: test_button
        align: CENTER
        width: 240
        height: 100
        text: "TOUCH ME"

        on_click:
          - logger.log: "LVGL BUTTON CLICKED"